version: '3.3'

services:

 db:
  image: postgres
  restart: always
  environment:
   POSTGRES_USER: debts
   POSTGRES_PASSWORD: debts
   POSTGRES_DB: debts
  ports:
   - "5432:5432"
  networks:
   - my-network
  volumes:
   - db-data:/var/lib/postgresql/data

 redis:
  image: redis
  ports:
   - "6379:6379"
  volumes:
   - redis-data:/data
  networks:
   - my-network

 app:
  image: kyrylchernov/debts-back
  restart: always
  ports:
   - "80:8080"
  depends_on:
   - db
   - redis
  networks:
   - my-network

networks:
 my-network:

volumes:
 db-data:
 redis-data: