version: '3.3'

services:

 db:
  image: postgres
  restart: always
  environment:
   POSTGRES_USER: debts
   POSTGRES_PASSWORD: debts
   POSTGRES_DB: debts
  ports:
   - "5432:5432"
  networks:
   - my-network
  volumes:
   - db-data:/var/lib/postgresql/data

 app:
  image: kyrylchernov/debts-back:0.01
  restart: always
  ports:
   - "80:8080"
  depends_on:
   - db
  networks:
   - my-network

networks:
 my-network:

volumes:
 db-data: