version: '3.3'

services:

 db:
  image: postgres
  restart: always
  environment:
   POSTGRES_USER: debts
   POSTGRES_PASSWORD: debts
   POSTGRES_DB: debts
  ports:
   - "5435:5432"
  networks:
   - my-network

 app:
  image: debts
  restart: always
  ports:
   - "8080:8080"
  depends_on:
   - db
  networks:
   - my-network

networks:
 my-network:
